language: clojure
lein: 2.7.1
before_script:
  - npm install -g eclint
  - eclint check .* * src/**/*.clj test/**/*.clj
  - lein install
  - lein cljfmt check
script:
  - lein with-profile +dev cloverage --coveralls
after_success:
  - curl -F 'json_file=@target/coverage/coveralls.json' 'https://coveralls.io/api/v1/jobs'
jdk:
  - oraclejdk8
